const GENERIC_TAGS = new Set([
  "ai",
  "assistant",
  "content",
  "productivity",
  "workflow",
]);

const CANONICAL_TAGS = [
  "ai",
  "assistant",
  "api",
  "accounting",
  "analytics",
  "audio",
  "automation",
  "browser",
  "cloud",
  "chatbot",
  "collaboration",
  "communication",
  "content",
  "crm",
  "customer-support",
  "data",
  "design",
  "developer-tools",
  "education",
  "email-productivity",
  "enterprise",
  "file-conversion",
  "finance",
  "helpdesk",
  "hr",
  "image",
  "language",
  "llm",
  "machine-learning",
  "marketing",
  "meeting",
  "mobile",
  "music",
  "nlp",
  "notes",
  "no-code",
  "open-source",
  "payroll",
  "productivity",
  "project-management",
  "prototyping",
  "research",
  "sales",
  "search",
  "scheduling",
  "seo",
  "social-media",
  "spreadsheet",
  "test-automation",
  "translation",
  "transcription",
  "video",
  "voice",
  "web",
  "whiteboard",
  "workflow",
  "writing",
  "creative",
];

const CANONICAL_SET = new Set(CANONICAL_TAGS);

const DIRECT_ALIASES = new Map([
  ["produktivitat", "productivity"],
  ["produktivitat", "productivity"],
  ["produktivitaet", "productivity"],
  ["chatbots", "chatbot"],
  ["assistanten", "assistant"],
  ["assistent", "assistant"],
  ["copilot", "assistant"],
  ["helper", "assistant"],
  ["app-builder", "no-code"],
  ["copywriting", "writing"],
  ["copy", "writing"],
  ["article", "content"],
  ["artikel", "content"],
  ["blog", "content"],
  ["text", "writing"],
  ["texte", "writing"],
  ["editor", "writing"],
  ["content-marketing", "content"],
  ["social", "social-media"],
  ["browser-based", "browser"],
  ["browserbased", "browser"],
  ["editing", "video"],
  ["companion", "assistant"],
  ["software", "productivity"],
  ["library", "research"],
  ["python", "developer-tools"],
  ["java", "developer-tools"],
  ["framework", "developer-tools"],
  ["pdf", "file-conversion"],
  ["vector", "design"],
  ["generation", "creative"],
  ["localization", "translation"],
  ["follow-ups", "productivity"],
  ["follow-ups", "productivity"],
  ["rpa", "automation"],
  ["business-travel", "scheduling"],
  ["travel-management", "scheduling"],
  ["color-grading", "video"],
  ["deepfakes", "video"],
  ["distributed-computing", "cloud"],
  ["kubernetes", "cloud"],
  ["entertainment", "creative"],
  ["grammar-checking", "writing"],
  ["lifestyle", "productivity"],
  ["microsoft-365", "productivity"],
  ["psa", "project-management"],
  ["workspace", "productivity"],
  ["apple", "mobile"],
  ["keyboard", "productivity"],
  ["availability", "scheduling"],
  ["brainstorming", "collaboration"],
  ["agent", "assistant"],
  ["acceleration", "productivity"],
  ["math", "education"],
  ["azure", "cloud"],
  ["visualization", "analytics"],
  ["data-visualization", "analytics"],
  ["devtools", "developer-tools"],
  ["developer", "developer-tools"],
  ["developers", "developer-tools"],
  ["programming", "developer-tools"],
  ["code", "developer-tools"],
  ["code-completion", "developer-tools"],
  ["code-intelligence", "developer-tools"],
  ["code-search", "developer-tools"],
  ["cloud-ide", "developer-tools"],
  ["remote-development", "developer-tools"],
  ["ide", "developer-tools"],
  ["cli", "developer-tools"],
  ["sdk", "developer-tools"],
  ["github", "developer-tools"],
  ["webdriver", "test-automation"],
  ["testing", "test-automation"],
  ["ui-testing", "test-automation"],
  ["api-testing", "test-automation"],
  ["qa", "test-automation"],
  ["low-code", "no-code"],
  ["lowcode", "no-code"],
  ["website-builder", "no-code"],
  ["cms", "no-code"],
  ["app-development", "no-code"],
  ["appdevelopment", "no-code"],
  ["business-app", "no-code"],
  ["workflowautomation", "automation"],
  ["workflow-automation", "workflow"],
  ["automate", "automation"],
  ["zapier", "automation"],
  ["n8n", "automation"],
  ["ifttt", "automation"],
  ["copy-editing", "writing"],
  ["documentation", "productivity"],
  ["documents", "productivity"],
  ["document", "productivity"],
  ["utilities", "productivity"],
  ["online-tools", "productivity"],
  ["planning", "productivity"],
  ["task-management", "project-management"],
  ["work-management", "project-management"],
  ["projectmanagement", "project-management"],
  ["process-management", "workflow"],
  ["resource-planning", "project-management"],
  ["workflowmanagement", "workflow"],
  ["calendar", "scheduling"],
  ["booking", "scheduling"],
  ["appointments", "scheduling"],
  ["meeting-planning", "meeting"],
  ["meetingplanning", "meeting"],
  ["email", "email-productivity"],
  ["gmail", "email-productivity"],
  ["inbox", "email-productivity"],
  ["shared-inbox", "customer-support"],
  ["live-chat", "customer-support"],
  ["ticketing", "customer-support"],
  ["helpdesk", "customer-support"],
  ["lead-generation", "sales"],
  ["newsletter", "marketing"],
  ["ads", "marketing"],
  ["content-marketing", "marketing"],
  ["keyword-research", "seo"],
  ["search-engine-optimization", "seo"],
  ["google-tabellen", "spreadsheet"],
  ["excel", "spreadsheet"],
  ["spreadsheets", "spreadsheet"],
  ["sheets", "spreadsheet"],
  ["citations", "research"],
  ["citation", "research"],
  ["bibliometrics", "research"],
  ["reference-management", "research"],
  ["reference-manager", "research"],
  ["publication", "research"],
  ["publications", "research"],
  ["literature-review", "research"],
  ["topic-modeling", "research"],
  ["academic-search", "research"],
  ["academic-networking", "research"],
  ["academic-research", "research"],
  ["research-assistant", "research"],
  ["search", "search"],
  ["ai-search", "search"],
  ["keyword-research", "search"],
  ["conversation", "chatbot"],
  ["dialogue", "chatbot"],
  ["chat", "chatbot"],
  ["speech", "voice"],
  ["tts", "voice"],
  ["podcast", "audio"],
  ["podcasting", "audio"],
  ["audio-video", "video"],
  ["video-editing", "video"],
  ["consumer-video", "video"],
  ["streaming", "video"],
  ["filmmaking", "video"],
  ["storyboarding", "video"],
  ["post-production", "video"],
  ["pre-production", "video"],
  ["photo-editing", "image"],
  ["image-editing", "image"],
  ["image-generation", "image"],
  ["imageediting", "image"],
  ["photo", "image"],
  ["photography", "image"],
  ["graphics", "image"],
  ["illustration", "image"],
  ["picture", "image"],
  ["visualization", "analytics"],
  ["wireframing", "design"],
  ["ui-design", "design"],
  ["ux", "design"],
  ["ui", "design"],
  ["prototyping", "design"],
  ["whiteboard", "collaboration"],
  ["creative-tools", "creative"],
  ["creator-tools", "creative"],
  ["creative-learning", "creative"],
  ["digital-painting", "creative"],
  ["music-production", "music"],
  ["music-generation", "music"],
  ["daw", "music"],
  ["music", "music"],
  ["voiceover", "voice"],
  ["vocal", "voice"],
  ["machine-learning", "machine-learning"],
  ["mlops", "machine-learning"],
  ["automl", "machine-learning"],
  ["deep-learning", "machine-learning"],
  ["inference", "machine-learning"],
  ["big-data", "data"],
  ["data-engineering", "data"],
  ["data-integration", "data"],
  ["data-preparation", "data"],
  ["data-warehouse", "data"],
  ["etl", "data"],
  ["data-science", "data"],
  ["analytics", "analytics"],
  ["dashboard", "analytics"],
  ["dashboards", "analytics"],
  ["benchmark", "data"],
  ["experiments", "data"],
  ["reproducibility", "data"],
  ["enterprise-software", "enterprise"],
  ["enterprise-ai", "enterprise"],
  ["hcm", "hr"],
  ["talent-management", "hr"],
  ["payroll", "payroll"],
  ["invoice", "accounting"],
  ["invoices", "accounting"],
  ["bookkeeping", "accounting"],
  ["accounting", "accounting"],
  ["finance", "finance"],
  ["browser-based", "browser"],
  ["desktop", "web"],
  ["mobile-app", "mobile"],
  ["translation-management", "translation"],
  ["nmt", "translation"],
  ["cat-tools", "translation"],
  ["language-tools", "language"],
  ["language-learning", "education"],
  ["study", "education"],
  ["agile", "project-management"],
  ["work-management", "project-management"],
  ["communication", "communication"],
  ["messaging", "communication"],
  ["social-media", "social-media"],
  ["social-media-management", "social-media"],
  ["social-media-marketing", "social-media"],
  ["browser", "browser"],
  ["cloud", "cloud"],
  ["open-source", "open-source"],
  ["web", "web"],
]);

const RULES = [
  [/^chat(bot|bots|chat|conversation|dialogue)s?$/, "chatbot"],
  [/assistant|copilot|helper/, "assistant"],
  [/writing|copywriting|blog|article|editor|text|copy|scriptwriting/, "writing"],
  [/content-marketing|content/, "content"],
  [/marketing|newsletter|ads|lead-generation/, "marketing"],
  [/seo|search-engine-optimization|keyword-research/, "seo"],
  [/social[- ]?media|^social$/, "social-media"],
  [/design|ui|ux|wireframing|prototyping|presentation|whiteboard/, "design"],
  [/creative-tools|creator-tools|creative-learning|digital-painting/, "creative"],
  [/image|photo|photography|illustration|graphics|art|visualization/, "image"],
  [/video|filmmaking|storyboarding|pre-production|post-production|streaming|consumer-video/, "video"],
  [/audio|podcast|sound/, "audio"],
  [/voice|speech|tts/, "voice"],
  [/transcription/, "transcription"],
  [/productivity|documents?|utilities|online-tools|planning/, "productivity"],
  [/automation|automate|zapier|n8n|ifttt/, "automation"],
  [/workflow/, "workflow"],
  [/no[- ]?code|low[- ]?code|cms|website-builder|app[- ]?development|app[- ]?builder/, "no-code"],
  [/analytics|dashboard/, "analytics"],
  [/data-science/, "data"],
  [/machine-learning|automl|mlops|deep-learning|inference|benchmark|experiments|reproducibility/, "machine-learning"],
  [/big-data|data-engineering|data-integration|data-preparation|data-warehouse|etl/, "data"],
  [/spreadsheet|sheets?|excel|google-tabellen/, "spreadsheet"],
  [/crm/, "crm"],
  [/sales|lead-generation/, "sales"],
  [/code|coding|programming/, "developer-tools"],
  [/developer|devtools|sdk|github|cli|cloud-ide|remote-development|ide|webdriver|api-testing/, "developer-tools"],
  [/api/, "api"],
  [/test|testing|ui-testing|api-testing/, "test-automation"],
  [/translation|nmt|cat-tools/, "translation"],
  [/language-tools|language-learning/, "language"],
  [/education|study/, "education"],
  [/customer-support|helpdesk|shared-inbox|ticketing|live-chat/, "customer-support"],
  [/meeting-planning|meeting/, "meeting"],
  [/calendar|booking|appointments|schedule|scheduling/, "scheduling"],
  [/research|citation|citations|bibliometric|reference|publication|literature-review|topic-modeling|academic/, "research"],
  [/collaboration|whiteboard/, "collaboration"],
  [/llm|gpt|conversation|dialogue/, "llm"],
  [/enterprise/, "enterprise"],
  [/search/, "search"],
  [/notes?/, "notes"],
  [/finance/, "finance"],
  [/accounting|bookkeeping|invoice/, "accounting"],
  [/browser-based|browser/, "browser"],
  [/cloud|distributed-computing/, "cloud"],
  [/open-source/, "open-source"],
  [/project-management|work-management|resource-planning|task-management|process-management/, "project-management"],
  [/communication|messaging|inbox|email/, "communication"],
  [/nlp/, "nlp"],
  [/music|podcast/, "music"],
  [/hr|hcm|talent-management/, "hr"],
  [/payroll/, "payroll"],
  [/web/, "web"],
  [/mobile/, "mobile"],
];

function asciiKey(value) {
  return String(value || "")
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replace(/[_\s]+/g, "-")
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function canonicalizeTag(tag) {
  const key = asciiKey(tag);
  if (!key) return "";
  if (CANONICAL_SET.has(key)) return key;
  if (DIRECT_ALIASES.has(key)) return DIRECT_ALIASES.get(key);
  for (const [pattern, canonical] of RULES) {
    if (pattern.test(key)) return canonical;
  }
  return key;
}

export function normalizeTags(input = [], { maxTags = 5, preserveUnknown = true } = {}) {
  const rawTags = Array.isArray(input)
    ? input
    : String(input || "")
        .split(/[;,]/)
        .map((t) => t.trim())
        .filter(Boolean);

  const seen = new Set();
  const normalized = [];
  const unresolved = [];

  for (const raw of rawTags) {
    const canonical = canonicalizeTag(raw);
    const isKnown = CANONICAL_SET.has(canonical);
    if (!isKnown && !preserveUnknown) {
      unresolved.push(String(raw || "").trim());
      continue;
    }
    const out = isKnown ? canonical : asciiKey(raw);
    if (!out) continue;
    if (!seen.has(out)) {
      seen.add(out);
      normalized.push(out);
    }
    if (!isKnown) unresolved.push(out);
  }

  return {
    tags: normalized.slice(0, maxTags),
    unresolved: [...new Set(unresolved)],
  };
}

export function hasGenericTags(tags = []) {
  const normalized = normalizeTags(tags, { maxTags: 20, preserveUnknown: true }).tags;
  if (normalized.length === 0) return true;
  return normalized.every((t) => GENERIC_TAGS.has(t));
}

export function isCanonicalTag(tag) {
  return CANONICAL_SET.has(String(tag || "").trim().toLowerCase());
}

export { CANONICAL_TAGS, GENERIC_TAGS };
